### PR TITLE
Update ja-JP.json

### PR DESCRIPTION
**Pull request by Sunny-JP**
Translated feedback and resource downloads. Also, some translations were corrected.
P.S.: I know you are also working on a StarRail version, and if you make it multilingual, please let me know as I'd like to help you.

### CODE REVIEW

**Review by AguzzTN54 — APPROVED** [review]

**Comment by AguzzTN54** [comment]
Oh, Thank You very much, The HSR Sim is 80% ready for multilingual feature, I will make the repository public once it's ready.

**Comment by Sunny-JP** [comment]
I just noticed you added a fancy payment method, lol
Please add wallets (=Tartaglia) as well!

**Comment by AguzzTN54** [comment]
Hahaha, Nice Idea 😂

**Comment by AguzzTN54** [comment]
HSR Warp Simulator is ready for multilingual features, you can check [this repository](https://github.com/AguzzTN54/HSR-Warp-Simulator) if you want to know.

**Comment by Sunny-JP** [comment]
ok, I checked.
Translation will take a few days, but please be patient~

**Comment by AguzzTN54** [comment]
No problem, I'm in no rush, Thanks.

**Pull request merged**
