### PR TITLE
Updating 5star.mp4

### PR DESCRIPTION
**Pull request by ScarletSeal**
Less laggy meteor animation. I got it by splicing 5star-single.mp4 and 5star.mp4 together. 
The result is seamless, UID is not shown, and there's no audio/video warping.

### CODE REVIEW

**Review by AguzzTN54 — CHANGES_REQUESTED** [review]
I think it's too big, can you make it around 3MB - 4MB ?
Reducing the bitrate will also reduce the file size. The other meteor animation videos have around 5000 - 6000 kbps, but your video has 12000 kbps bitrate.

**Comment by ScarletSeal** [comment]
Bumped the bitrate down to 5000. New file size is 3.75 MB

**Review by AguzzTN54 — APPROVED** [review]

**Comment by AguzzTN54** [comment]
Excuse me, I haven't merged it yet. 😅
I was a bit busy earlier, so I just approved and ran code checker. I want to merge it now, but you already deleted the head repository.

**Comment by ScarletSeal** [comment]
Oh, I didn't know that deleting the repository would also delete the pull request, how dumb of me
I'll try again 😅

**Pull request closed without merging**
